---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi
  labels:
    name: nifi
    app: nifi
  annotations:
    app.kubernetes.io/name: nifi
    app.kubernetes.io/part-of: nifi
spec:
  revisionHistoryLimit: 1
  serviceName: nifi
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      restartPolicy: Always
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: wait-for-zookeeper
          image: docker.io/busybox:1.36
          command:
          - sh
          - -c
          - |
            echo "Connecting to Zookeeper ${NIFI_ZK_CONNECT_STRING}"
            until nc -vzw 1 zookeeper 2181 ; do
              echo "Waiting for zookeeper to start"
              sleep 3
            done
          envFrom:
          - configMapRef:
              name: nifi-cm
              optional: false
          resources:
            requests:
              cpu: 20m
              memory: 10Mi
            limits:
              cpu: 20m
              memory: 10Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      containers:
      - name: nifi
        image: docker.io/apache/nifi:1.21.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 11443
          name: cluster
        - containerPort: 8443
          name: https
        - containerPort: 6342
          name: cluster-lb
        env:
          - name: NIFI_WEB_HTTP_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NIFI_CLUSTER_NODE_ADDRESS
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NIFI_REMOTE_INPUT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NODE_IDENTITY
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        envFrom:
          - configMapRef:
              name: nifi-cm
              optional: false
        volumeMounts:
          - name: data
            mountPath: /opt/nifi/nifi-current/data
            subPath: data
            readOnly: false
          - name: data
            mountPath: /opt/nifi/nifi-current/keytool
            subPath: keytool
            readOnly: false
          - name: scripts
            mountPath: /scripts/security.sh
            subPath: security.sh
            readOnly: false
          - name: lecnars
            mountPath: /opt/nifi/nifi-current/extensions/
        lifecycle:
          postStart:
            exec:
              command:
                - /scripts/security.sh
        livenessProbe:
          exec:
            command:
              - pgrep
              - java
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          tcpSocket:
            port: cluster
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        resources:
          requests:
            cpu: 2
            memory: 2Gi
          limits:
            cpu: 2
            memory: 2Gi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          capabilities:
            drop:
              - ALL
      volumes:
        - name: data
          emptyDir:
            sizeLimit: 10Gi
        - name: scripts
          configMap:
            name: nifi-ssl-cm
            optional: false
            defaultMode: 0755
        - name: lecnars
          hostPath:
            path: /datadrive1/lec-connectors
            type: Directory
        - name: lecdata
          hostPath:
            path: /datadrive0
            type: Directory
              sizeLimit: 10Gi
